### ISSUE TITLE
Escaped characters in settings

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/ESP32-RevK#11]
After i press "Set" on /wifi settings page, httpd_query_key_value() returns raw, escaped values. I have already fixed this with "as+is" in password field; and here it comes again corrupting timezone setting.

There are two possibilities:
1. On ESP32 httpd_query_key_value() unescapes strings itself.
2. You just don't test "Set" button because websockets work for you.

Which one is that ?

**Comment by Sonic-Amiga** [comment]
My patch to fix this is here https://github.com/Sonic-Amiga/ESP32-RevK/commit/7132501097f6b923ed764f5c7747115b3411f940 , but depending on your answer we may need to modify it.

**Comment by revk** [comment]
I would have to check. I have indeed been using web sockets. It would be crazy not to unescape it, so it did not occur me to check! I'll have to do a test.

**Comment by revk** [comment]
Test confirm it is not de-escaped, so included in **https://github.com/revk/ESP32-RevK/issues/12**
