### ISSUE TITLE
setting/<hostname> missing "dark" setting

### ISSUE THREAD

**Issue by lorbetzki** [revk/ESP32-RevK#14]
Hi,

after i'm sending a setting/<hostname> to the device i receive many values, but dark is missing
```{"rx":-27,"tx":-26,"reporting":60,"tcontrol":600,"tsample":900,"tpredictt":120,"tpredicts":30,"tmax":32,"tmin":16,"push10":1,"switch10":5,"heatback":6,"heatover":6,"coolback":6,"coolover":6,"autop10":5,"thermref":50,"uart":1,"ha":true,"protocol":1,"webcontrol":2,"mqtt":[{"port":1883,"pass":"BLA","user":"mqtt","host":"192.168.146.47"}],"wifi":{"pass":"BLABLA","ssid":"Wifi","reset":3600},"blink":[-8,-19,-7],"hostname":"ac","appname":"Faikin","watchdogtime":60,"tz":"GMT+0BST,M3.5.0,M10.5.0","ntphost":"pool.ntp.org","otaauto":7,"otahost":"ota.revk.uk","prefix":{"error":"error","info":"info","event":"event","state":"state","setting":"setting","command":"command"}}```

Best regards

**Comment by revk** [comment]
Have you set it - if default (off) it won't list I don't think.

Send `setting/name/dark 1` and then try.

**Comment by lorbetzki** [comment]
ah! you are right. I was hoping it would send false. thx.
