### ISSUE TITLE
Wi-Fi Passphrase isn't hidden any more

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/ESP32-RevK#19]
In older version of Faikin (and RevK lib) "Passphrase" field had "hidden text" attribute (it displayed dots); while now it displays current password in clear text. Is this an overlook or intentional change ?
Maybe keep the password hidden by default and implement "See it" button like other people do ?

**Comment by revk** [comment]
It used to actually not be sent at all, sent as *'s, but the settings has been made more generic now to allow more settings depending on the application. But making it standard "hidden" is easy though, so I can do that.

**Comment by Sonic-Amiga** [comment]
Actually no. I've just tried typing in that field; and i saw dots instead of characters i'm typing. But, nevermind. Would be nice to see standard behavior.

**Comment by revk** [comment]
Ah sorry, I think maybe even it did both, but yeh, should be sensible now.

**Comment by Sonic-Amiga** [comment]
Yes, i am starting to recall that in very old version you had a special string like "no change" or something like that.
