### ISSUE TITLE
New libRevK is totally un-buildable under Windows

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/ESP32-RevK#24]
revk_settings is written in a completely unportable manner. It uses getline(), strndup(), err(), errx(), which aren't available even on MinGW.

Ideally it shouldn't even require a makefile because, again, ESP32 SDK on Windows is a naked cmd.exe; no POSIX stuff whatsoever; everything is python-based.

**Comment by revk** [comment]
Not a fan of python, and I don't use windows!

**Comment by Sonic-Amiga** [comment]
I use Windows, sorry for that.
I am also a python hater; but unfortunately Espressif has decided everything for us :(

Well, i've done some quick patching, now i can get around at least somehow. And yes, in 8266 i won't have problems at all because that one perfectly runs in MinGW shell; where you have bash, make, gcc and everything

**Comment by revk** [comment]
Err and errx are easy to make something for, and so is strdup.

Getline is great, does it really ok do that?

I mean if you want to make a python version, do. But I bet it could be made to windows with a few #ifdef and some local versions of functions.
