### ISSUE TITLE
Re-test AP mode settings on Android

### ISSUE THREAD

**Issue by revk** [revk/ESP32-RevK#3]
Reported as not working, so needs testing.

Also, find out if any way to "splash page" on Android like we do on iPhone.

**Comment by WheresWes** [comment]
subscribed

**Comment by Sonic-Amiga** [comment]
Works great for me; i am just lazy to add a proper detection URL.
A list of known detection URLs can be found here https://en.wikipedia.org/wiki/Captive_portal , see "Detection" paragraph. In fact nothing stops you from implementing them all
