### ISSUE TITLE
"debug" setting isn't listed even in advanced mode

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/ESP32-RevK#31]
Is there any particular strong reason for that ? It turns out not all users know how to handle mqtt on low level.

Frankly speaking even i forgot all message formats after pause in development. Fortunately mqttx keeps history.

**Comment by revk** [comment]
![image](https://github.com/revk/ESP32-RevK/assets/996983/821b729a-2f6b-462f-924c-be9715779700)

**Comment by revk** [comment]
Just realised this is raised in the library. Does the library even have debug as a setting?

On Faikin, for example, it is listed...

![image](https://github.com/revk/ESP32-RevK/assets/996983/5dc861db-6f7d-4ed4-b486-ec8981c72962)

**Comment by revk** [comment]
The library does not have a `debug` setting.

**Comment by Sonic-Amiga** [comment]
I thought everything under settings/ is managed by the library.
Does the app have to do anything to register these extra settings ? I thought it's all merged in one settings.c 

Looked at the generated file. There's a descriptor for each setting, and it has .ptr, specifying storage pointer:
```
{.type=REVK_SETTINGS_UNSIGNED,.name="thermref",.len=8,.def="50",.ptr=&thermref,.size=sizeof(uint8_t),.live=1},
```
But for bit fields there's no such thing:
```
{.type=REVK_SETTINGS_BIT,.name="debug",.len=5,.bit=REVK_SETTINGS_BITFIELD_debug,.live=1},
```
 How does the lib know where to store it ? Could that be a cuplrit ?

**Comment by revk** [comment]
The is documented! [New settings](https://github.com/revk/ESP32-RevK/blob/master/revk-settings.md)

`settings.def` typically in the app lists the apps additional settings. You could have multiple files, depends on the build.

All of the settings files result in `settings.c` and `settings.h`

The faikin build has `debug` in `settings.def`, and as long as it has a comment, as it does in my build, it will appear in advanced settings.

```
bit     debug                           .live=1                                 // Debug (extra messages and list replies)
```

```
 {.type=REVK_SETTINGS_BIT,.name="debug",.comment="Debug (extra messages and list replies)",.len=5,.bit=REVK_SETTINGS_BITFIELD_debug,.live=1},
```

**Comment by revk** [comment]
The `.ptr` is for the target, but for bitfields they are placed in a `struct revk_settings_bits_s` with a `#define`, and the `.bit` specifies which bit it is in that structure. This ensures bit fields take only one bit in memory.

**Comment by Sonic-Amiga** [comment]
Thank you for hinting. It boils down to "// Description" , which appears to be not just a comment, but also what pops up on the web interface. If unset, the setting is hidden. Your revk-settings-dev.md doesn't seem to mention it. It only says "optional comment", and all the devs know that comments are for human readers only, they are ignored during compilation.

**Comment by Sonic-Amiga** [comment]
I was conservative and took the very first version of settings.def for the app. It's missing descriptions, that's why...

**Comment by revk** [comment]
I have updated the manual now, by the way. The advanced settings are a new feature.
